/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElInputPassword: (typeof import('element-plus/es'))['ElInputPassword']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    'IEp-{{': (typeof import('~icons/ep/{{'))['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpIceCreamRound: (typeof import('~icons/ep/ice-cream-round'))['default']
    'IEpItem.icon': (typeof import('~icons/ep/item.icon'))['default']
    IEpLock: (typeof import('~icons/ep/lock'))['default']
    IEpNotification: (typeof import('~icons/ep/notification'))['default']
    IEpPlus: (typeof import('~icons/ep/plus'))['default']
    IEpSetting: (typeof import('~icons/ep/setting'))['default']
    IEpUser: (typeof import('~icons/ep/user'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
